# Generated by Django 4.2.4 on 2023-08-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_storehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='max_working_hours',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='employee',
            name='min_working_hours',
            field=models.IntegerField(default=10),
        ),
    ]
