# Generated by Django 4.2.4 on 2023-08-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_employee_max_working_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='max_working_hours',
            new_name='max_working_hours_weekly',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='min_working_hours',
            new_name='min_working_hours_weekly',
        ),
        migrations.RenameField(
            model_name='employeeavailability',
            old_name='end_time',
            new_name='end_hour',
        ),
        migrations.RenameField(
            model_name='employeeavailability',
            old_name='start_time',
            new_name='start_hour',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
