# Generated by Django 4.2.4 on 2023-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_rename_max_working_hours_employee_max_working_hours_weekly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='end_friday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Friday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_monday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Monday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_saturday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Saturday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_sunday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Sunday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_thursday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Thursday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_tuesday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Tuesday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_wednesday',
            field=models.PositiveIntegerField(default=17, help_text='End hour for Wednesday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_friday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Friday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_monday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Monday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_saturday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Saturday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_sunday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Sunday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_thursday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Thursday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_tuesday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Tuesday (0-23)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_wednesday',
            field=models.PositiveIntegerField(default=8, help_text='Start hour for Wednesday (0-23)'),
        ),
        migrations.DeleteModel(
            name='EmployeeAvailability',
        ),
    ]
